Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/data_migrate_after_db/*.rb'
    - 'db/data_migrate_before_db/*.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/data_migrate_after_db/*.rb'
    - 'db/data_migrate_before_db/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/data_migrate_after_db/*.rb'
    - 'db/data_migrate_before_db/*.rb'

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 240

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/**'
  IgnoredMethods:
    - included
