Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 240

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
