Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - usa
    - russia
    - staging
    - testing
    - proximity_testing
    - test
    - development
