RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/NestedGroups:
  Max: 6
  
RSpec/FilePath:
  Exclude:
    - 'spec/requests/**/*.rb'
